version: '3'

tasks:
  docs:
    cmds:
      - swag init -g cmd/server/main.go -o docs

  run:
    deps: [docs]
    cmds:
      - go run cmd/server/main.go

  dev:
    deps: [docs]
    cmds:
      - air

  build:
    deps: [docs]
    cmds:
      - go build -o bin/server cmd/server/main.go
