version: '3'

tasks:
  swagger:
    cmds:
      - swag init -g cmd/server/main.go -o cmd/swag/docs

  run:
    deps: [swagger]
    cmds:
      - go run cmd/server/main.go

  dev:
    deps: [swagger]
    cmds:
      - air

  build:
    deps: [swagger]
    cmds:
      - go build -o bin/server cmd/server/main.go
